version: '3'

services:
  llm:
    build:
      context: ./llm  # Directory containing the Dockerfile for the first application
    ports:
      - "4000:4000"

  elasticsearch:
    build: 
      context: ./elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  object-detection:
    build:
      context: ./object-detection  # Directory containing the Dockerfile for the second application
    ports:
      - "6000:6000"  
    depends_on:
      - llm  # Ensure that the llm container is started before yolov5-app

  search:
    build:
      context: ./search  # Directory containing the Dockerfile for the second application
    ports:
      - "8000:8000"  
    depends_on:
      - elasticsearch
      - object-detection  # Ensure that the object-detection container is started before yolov5-app